config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'flats#index'

  get "/flats/:id", to: "flats#show", as: :flat
  get "/flats", to: "flats#index", as: :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  FLAT_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  before_action :load_flats, only: [:index, :show]

  def index
  end

  def show
    @flat = @flats.find do |flat_hash|
      flat_hash['id'] == params[:id].to_i
    end
  end

  private
  def load_flats    
    @flats = JSON.parse(open(FLAT_URL).read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<% @flats.each do |flat| %>
  <%= link_to flat_path(flat['id']) do %>
    <div class="card">
      <img src="<%= flat['imageUrl'] %>" width="200" height="100%">
      <h3><%= flat["name"] %></h3>
    </div>
  <% end %>
<% end %>

app/views/flats/show.html.erb
<div class="card">
  <img src="<%= @flat['imageUrl'] %>" width="200" height="100%">
  <h3><%= @flat["name"] %></h3>
  <h4><%= "#{@flat['priceCurrency']} - #{@flat['price']}" %></h4>
</div>

<%= link_to "Back to all flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>